### PR TITLE
Multi thread support with unittest

### PR DESCRIPTION
**Pull request by FootStark**
OK, that was a real lesson in github. A warning: I had to remerge my changes after you renamed `unitttest `(triple_T). The changes in this PR look correct, so I hope I didn't mess it up.

The threading changes: I added support for multithreading in 2 levels, with a speedup of around 25% for 2-threads, and up to triple speed on decryption for 4 thread.
First level (2 threads) parallelizes decryption and HMAC-calculation by piping the data for de/encryption to a secondary thread. This works both for decryption and encryption.
Higher level (>2 threads) is only available for decryption. It splits the crypted input stream into chunks, repeats the last Block for CBC, and runs decryption on chunked data in a separate thread each. The data is then reassembled on read.
The desired threading level can be set via property `MaxCryptoThreads` which defaults to 1 (no multithreading).
The necessary work on streams is done in helper classes (subnamespace threading). `DirectStreamLink` is basically a buffering pipe, and `OverlappedStreamStriper` is for chunking and reassembling the data. 
The real magic (setting up and plugging the streams invloved) is done in `InitStreamsDecryption` and `InitStreamsEncryption`. I postponed stream initialization for decryption analoge to encryption, so the property for threading can be set.

Other changes: I updated `StreamHider` to store the hidden bytes even after the stream was closed. So all streams can be closed now directly after read to end.

Unittests:
I added a unit test for Multithreading that checks en-/decryption with 2-4 thread.
I added a unit test for truncated stream data, simulating a stream being cut short.
All threading tests do a basic check to detect deadlocks or non-ending threads.
I modified the basic unitttest to check well behaviour on wrong password and invalid HMAC.

Well, that's about it. If you have any troube verifying or understanding the code, let me know.
I ran a lot of tests, and also the unitttests passed.

### CODE REVIEW

**Comment by FootStark** [comment]
FYI: I saw the unittests couldn't pass, bulk testing takes to long.
So I reduced the bulk test repetitions and modified the Unittest to use categories. Travis will now perform the unittests in 2 phases: non-bulk and bulk.

**Comment by kenkendk** [comment]
Thanks for fixing the unittest! I did not know about the category attribute, but that is an elegant way to fix it.

For the update itself: great idea with the splitting of HMAC and encryption into two threads.
I have not gotten around all the changes yet, but it looks good so far.

**Comment by FootStark** [comment]
Yet I wasn't sure if the 120 min limit applies to the whole test or just each step in the script. That's why I reduced `REPETITIONS` in BulkTest to allow the whole test to pass in less than 2h. You might want to set it back to somewhere around 500 again (should be like 1,5h on average).
The main reason for introducing `Category` was to run BulkTest last without renaming it to like `Z_BulkTest`.

**Comment by FootStark** [comment]
To give you a little update on testing: I incorporated a private build of the updated SharpAESCrypt into duplicati for all my tests there, and ran it  on maximum thread-level. Until now, the library appeared to be fast and reliable.

I did also create a branch https://github.com/FootStark/duplicati/tree/TestIntegrateNewSharpAESCrypt that introduces a new parameter `aes-set-threadlevel` to be passed to the encryption module. But this would need a new official build first, so I will not start a pull request yet. I am away for the next week, but if you need it, you can pull it there.

**Pull request merged**
